version: '3.9'

services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: developer
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: movies
        ports:
            - '5432:5432'
    pgadmin:
        image: dpage/pgadmin4
        container_name: movies_pgadmin
        restart: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
            - '5051:443'
